from datetime import timedelta

DB_HOST = "127.0.0.1"
DB_USER = "root"
DB_PASSWORD = ""
DB_NAME = "finex_db"
DB_PORT = 3306

SECRET_KEY = "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"

SESSION_CONFIG = {
    "SESSION_COOKIE_SAMESITE": "Lax",
    "SESSION_COOKIE_SECURE": False,
    "PERMANENT_SESSION_LIFETIME": 3600
}